### PR TITLE
V9/dev

### PR DESCRIPTION
**Pull request by AaronSadlerUK**
My work so far

### CODE REVIEW

**Comment by KevinJump** [comment]
Hi, 

I am not sure what me pushing back to the PR has done ? - but that is the stub of middleware - that does work. 

if maintainance mode is on, the path is changes to /maintain. if your site has that page you would see that content, while the URL hasn't changed. 

next would be changing path to a route that will trigger a controller ? that you could then call the actual view for a maintainance page from ?

**Comment by KevinJump** [comment]
Hi - looking good shall i merge this now ?

**Comment by AaronSadlerUK** [comment]
All that's left is moving some bits in the angular controllers and views to the lang file

**Comment by KevinJump** [comment]
OK - no worries I can pick those up as i go through it.

**Comment by AaronSadlerUK** [comment]
Yeah sure, ill mark it as ready

**Comment by AaronSadlerUK** [comment]
Oh ha you beat me to it 😅

**Pull request merged**
